version: "3.10"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/nofrixion-for-woocommerce
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8821:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      CURLOPT_SSL_VERIFYPEER: 0
      CURLOPT_SSL_VERIFYHOST: 0
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
volumes:
  db_data: {}
  wordpress_data: {}
